version: '3.8'

services:
    localstack:
        container_name: "localstack_main"
        image: localstack/localstack:latest
        environment:
            - SERVICES=dynamodb,lambda,apigateway,s3,iam,cloudwatch,kms
            - LAMBDA_EXECUTOR=local
            - LAMBDA_REMOTE_DOCKER=false
            - DOCKER_HOST=unix:///var/run/docker.sock
            - DEFAULT_REGION=us-east-1
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
            - PORT_WEB_UI=8080
        ports:
            - "53:53"
            - "53:53/udp"
            - "443:443"
            - "4566:4566"
            - "4571:4571"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - localstack_data:/tmp/localstack/data
        networks:
            default:

volumes:
    localstack_data:
networks:
    default:
        name: localstack-tokenizer
